# Generated by Django 5.1.2 on 2024-10-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomedia',
            name='status',
            field=models.CharField(choices=[('UPLOAD_STARTED', 'Upload iniciado'), ('PROCESS_STARTED', 'Processamento iniciado'), ('PROCESS_FINISHED', 'Processamento finalizado'), ('PROCESS_ERROR', 'Erro no processamento')], default='UPLOAD_STARTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video_media', to='core.video', verbose_name='Video'),
        ),
    ]
