services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "db"
      POSTGRES_SSL_MODE: "disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERSION_EXCHANGE: "conversion_exchange"
      CONVERSION_QUEUE: "video_conversion_queue"
      CONVERSION_KEY: "conversion"
      CONFIRMATION_KEY: "finish-conversion"
      CONFIRMATION_QUEUE: "video_confirmation_queue"
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "converter"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  external-storage:
    external: true
